### ISSUE TITLE
Setting Kanban Board

### ISSUE THREAD

**Issue by tumainimaganiko** [tumainimaganiko/space-travelers#25]
we are a group of two people in this project.

-   Tumaini Maganiko
- Amanuel Belete

 Here is the link to the projects [Projects](https://github.com/tumainimaganiko/space-travelers/projects/1)

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job setting up the kanban board.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
